// Summon libraries.
use std::io;
use std::cmp::Ordering;
use rand::Rng;

// Call main module.
fn main() {
    // Let user know what's going on.
    println!("Guess the number!");
    // Sets secret_number to a value generated by a module from the rand library, within the range of 1-101 (which presents itself as 1-100).
    let secret_number = rand::thread_rng().gen_range(1..101);

    // FOR DEBUG: Uncomment to display secret number
    // println!("The secret number is: {}", secret_number);

    // Create a loop so that the game will continue beyond a singular guess.
    loop {
        // Ask user to input guess.
        println!("Please input your guess.");
        // Let mutable variable guess (meaning it can be changed) be a new string.
        let mut guess = String::new();
        // Summon stdin() from the io library
        io::stdin()
            // Use read_line on the mutable guess.
            .read_line(&mut guess)
            // If there is an error, it will tell the user that the application failed to read the line.
            .expect("Failed to read line");
        // Set guess to unsigned 32-bit integer type, set equal to match guess after having been trimmed of newline characters and parse it to pull the number.
        let guess: u32 = match guess.trim().parse(){
            // match Ok returns the number, match Err of any type continues downward and therefore restarts the loop.
            Ok(num) => num,
            Err(_) => continue,
        };

        // Show user what number they guessed.
        println!("You guessed: {}", guess);

        // Compare secret number and guess.
        match guess.cmp(&secret_number) {
            // Tell the user if the guess is too low, too high, or equal.
            Ordering::Less => println!("Sorry bud, that's way too low."),
            Ordering::Greater => println!("Slow your roll, man! That number's way too huge!"),
            Ordering::Equal => {
                println!("Yeah, buddy! You got it! You got it!!!");
                // If the guess is equal, we end the program.
                break;
            }
        }
    }
}
